<?php
/**
 * WhatsApp webhook — receive inbound events, normalize, buffer turns.
 * AI responses are generated by the Conversation Turn Engine (never directly here).
 */

require_once __DIR__ . '/../config.php';

if (!function_exists('meta_webhook_verify_ok')) {
    $domainFile = __DIR__ . '/../includes/domain.php';
    if (is_readable($domainFile)) {
        require_once $domainFile;
    }
}

if (!function_exists('meta_webhook_verify_ok')) {
    function meta_webhook_verify_ok(string $token): bool
    {
        if ($token === '') {
            return false;
        }
        foreach (['WEBHOOK_VERIFY_TOKEN', 'WHATSAPP_VERIFY_TOKEN'] as $name) {
            if (!defined($name)) {
                continue;
            }
            $expected = trim((string) constant($name));
            if ($expected !== '' && hash_equals($expected, $token)) {
                return true;
            }
        }
        return false;
    }
}

if ($_SERVER['REQUEST_METHOD'] === 'GET') {
    $mode = $_GET['hub_mode'] ?? $_GET['hub.mode'] ?? '';
    $token = $_GET['hub_verify_token'] ?? $_GET['hub.verify_token'] ?? '';
    $challenge = $_GET['hub_challenge'] ?? $_GET['hub.challenge'] ?? '';

    if ($mode === 'subscribe' && meta_webhook_verify_ok($token)) {
        http_response_code(200);
        header('Content-Type: text/plain; charset=utf-8');
        echo $challenge;
        exit;
    }

    if ($mode === '' && $token === '' && $challenge === '') {
        header('Content-Type: text/plain; charset=utf-8');
        http_response_code(200);
        echo 'WhatsApp webhook is online. Meta verifies with hub.mode=subscribe — opening this URL in a browser is normal.';
        exit;
    }

    http_response_code(403);
    exit;
}

require_once __DIR__ . '/../includes/db.php';
require_once __DIR__ . '/../includes/helpers.php';
require_once __DIR__ . '/../includes/whatsapp.php';
require_once __DIR__ . '/../includes/whatsapp-webhook-log.php';
require_once __DIR__ . '/../includes/whatsapp-inbound.php';
require_once __DIR__ . '/../includes/whatsapp-token.php';
require_once __DIR__ . '/../includes/whatsapp-oauth.php';
require_once __DIR__ . '/../includes/conversation-turn-engine.php';

function wa_webhook_log(string $message, array $context = []): void
{
    whatsapp_webhook_log_event($message, $context);
}

$payload = file_get_contents('php://input') ?: '';
$signature = $_SERVER['HTTP_X_HUB_SIGNATURE_256'] ?? null;
$isDiagnosePost = isset($_SERVER['HTTP_X_AILEADS_DIAGNOSE']) || isset($_SERVER['HTTP_X_AILEADS-DIAGNOSE']);

whatsapp_webhook_log_event($isDiagnosePost ? 'POST received (diagnose self-test)' : 'POST received (meta)', [
    'bytes'      => strlen($payload),
    'has_sig'    => $signature !== null && $signature !== '',
    'user_agent' => substr($_SERVER['HTTP_USER_AGENT'] ?? '', 0, 80),
]);

if (!verify_meta_signature($payload, $signature)) {
    $secret = whatsapp_meta_app_secret();
    $hint = ($secret === '' || $secret === 'your_app_secret')
        ? 'Meta App Secret is missing — set it in Admin → Integrations'
        : 'Meta App Secret does not match Meta App → Settings → Basic';
    whatsapp_webhook_log_event('REJECTED invalid signature', ['hint' => $hint]);
    http_response_code(403);
    exit;
}

@set_time_limit(300);
ignore_user_abort(true);

turn_engine_ensure_schema();

$data = json_decode($payload, true);
if (!$data || empty($data['entry'])) {
    http_response_code(200);
    echo 'OK';
    exit;
}

$leadIdsToProcess = [];

foreach ($data['entry'] as $entry) {
    foreach ($entry['changes'] ?? [] as $change) {
        $field = (string) ($change['field'] ?? '');
        $value = $change['value'] ?? [];
        $phoneId = (string) ($value['metadata']['phone_number_id'] ?? '');
        $messages = $value['messages'] ?? [];

        if (in_array($field, ['history', 'smb_app_state_sync', 'smb_message_echoes', 'account_update'], true)) {
            wa_webhook_log('Coexistence webhook received', ['field' => $field, 'phone_id' => $phoneId]);
            continue;
        }

        if ($phoneId === '' || $messages === []) {
            continue;
        }

        wa_webhook_log('Inbound message for phone_id=' . $phoneId, ['count' => count($messages)]);

        $bot = bot_resolve_by_whatsapp_phone_id($phoneId);
        if (!$bot) {
            wa_webhook_log('No active bot matched phone_id=' . $phoneId);
            continue;
        }

        $token = bot_whatsapp_token_plain((string) ($bot['whatsapp_token'] ?? ''));
        if ($token === false || $token === '') {
            wa_webhook_log('Could not decrypt WhatsApp token for bot #' . (int) $bot['id']);
            whatsapp_mark_token_failure((int) $bot['id'], 'Could not read saved token — reconnect in Bot Setup.');
            continue;
        }

        bot_whatsapp_heal_connection((int) $bot['id']);

        $contacts = $value['contacts'] ?? [];
        $contactNames = [];
        foreach ($contacts as $contact) {
            $waId = (string) ($contact['wa_id'] ?? '');
            if ($waId !== '') {
                $contactNames[$waId] = (string) ($contact['profile']['name'] ?? 'WhatsApp Lead');
            }
        }

        foreach ($messages as $msg) {
            $senderPhone = (string) ($msg['from'] ?? '');
            if ($senderPhone === '') {
                continue;
            }

            $msgType = (string) ($msg['type'] ?? '');
            if (!in_array($msgType, ['text', 'audio', 'image', 'video', 'document', 'sticker', 'location', 'contacts', 'interactive'], true)) {
                wa_webhook_log('Skipped unsupported message type=' . ($msgType !== '' ? $msgType : 'unknown'));
                continue;
            }

            $contactName = $contactNames[$senderPhone] ?? 'WhatsApp Lead';
            $result = turn_engine_ingest($bot, $phoneId, $token, $senderPhone, $msg, $contactName);

            if (!empty($result['duplicate'])) {
                wa_webhook_log('DUPLICATE_EVENT_IGNORED', ['wa_id' => $msg['id'] ?? '']);
                continue;
            }

            if (empty($result['success'])) {
                wa_webhook_log('Turn ingest failed', [
                    'error' => $result['error'] ?? 'unknown',
                    'from'  => $senderPhone,
                    'type'  => $msgType,
                ]);
                continue;
            }

            if (!empty($result['lead_id'])) {
                $leadIdsToProcess[(int) $result['lead_id']] = (int) $result['lead_id'];
            }

            wa_webhook_log('Message buffered for turn', [
                'turn_id'  => $result['turn_id'] ?? null,
                'lead_id'  => $result['lead_id'] ?? null,
                'type'     => $msgType,
                'wa_id'    => $msg['id'] ?? '',
            ]);
        }
    }
}

if ($leadIdsToProcess !== []) {
    $ids = array_values($leadIdsToProcess);

    // Ack Meta immediately; ingest() already scheduled the worker with debounce (5s after last bubble).
    http_response_code(200);
    echo 'OK';

    if (function_exists('fastcgi_finish_request')) {
        fastcgi_finish_request();
    }

    @set_time_limit(90);
    wa_webhook_log('Turn engine background wait', ['leads' => $ids]);
    turn_engine_dispatch_worker($ids);

    $bgMs = defined('TURN_BACKGROUND_MS') ? (int) TURN_BACKGROUND_MS : 45000;
    turn_engine_background_process($ids, $bgMs);
} else {
    http_response_code(200);
    echo 'OK';
}
