const { chromium } = require("playwright-core");
(async () => {
  const browser = await chromium.launch({ channel: "chrome", args: ["--hide-scrollbars"] });
  const page = await browser.newPage({ viewport: { width: 390, height: 844 } });
  await page.goto("http://localhost:4173/?v=35", { waitUntil: "networkidle" });
  await page.screenshot({ path: "header-390.png", clip: { x: 0, y: 0, width: 390, height: 72 } });
  await page.click("#dma-pub-toggle");
  await page.waitForTimeout(250);
  await page.screenshot({ path: "menu-open-390.png", clip: { x: 0, y: 0, width: 390, height: 520 } });
  await page.click("#dma-pub-toggle");
  await page.waitForTimeout(150);
  await page.locator("#dma-public-footer").scrollIntoViewIfNeeded();
  await page.waitForTimeout(150);
  const footer = page.locator("#dma-public-footer");
  await footer.screenshot({ path: "footer-390.png" });
  const cta = page.locator(".dma-cta-band");
  await cta.screenshot({ path: "cta-390.png" });
  const desktop = await browser.newPage({ viewport: { width: 1280, height: 800 } });
  await desktop.goto("http://localhost:4173/?v=35", { waitUntil: "networkidle" });
  await desktop.screenshot({ path: "header-desktop.png", clip: { x: 0, y: 0, width: 1280, height: 80 } });
  await desktop.locator("#dma-public-footer").scrollIntoViewIfNeeded();
  await desktop.locator("#dma-public-footer").screenshot({ path: "footer-desktop.png" });
  await desktop.locator(".dma-cta-band").screenshot({ path: "cta-desktop.png" });
  const headerText = await page.locator("#dma-pub-nav").innerText();
  const footerText = await page.locator("#dma-public-footer").innerText();
  const logoVisible = await page.locator("#dma-pub-nav > .dma-pub-logo").isVisible();
  console.log("NAV_TEXT=" + JSON.stringify(headerText));
  console.log("HEADER_LOGO_VISIBLE=" + logoVisible);
  console.log("FOOTER_HAS_COPY=" + footerText.includes("© Clinicos · Doctors My Agency · 2026"));
  await browser.close();
})().catch((e) => { console.error(e); process.exit(1); });
